#!/bin/bash

set -e

generate(){

  local SRCDIR=src
  local OUTDIR=out.temp

  redo-ifchange "$SRCDIR.srclist"
  
  tr '\n' '\0' <"$SRCDIR.srclist" | xargs -0 -n 1 printf "%s.src\0" | xargs -0 redo-ifchange
  
  read_src_file(){
    local srcfile="$1"
    local d="${srcfile%/*}"

    tr '\n' '\0' <"$srcfile" | xargs -0 -n 1 printf "%s/%s.src\0" "$d" | xargs -0 redo-ifchange
    while read f2; do
      printf "%s/%s\n" "$d" "$f2"
      if [ "a$d/$f2.src" != "a$srcfile" ]; then
        read_src_file "$d/$f2.src"
      fi
    done <"$srcfile"
  }
  
  list="$(
    while read f; do
      read_src_file "$f.src"
    done <"$SRCDIR.srclist")"
    
  echo "$list" | tr '\n' '\0' | xargs -0 -n 1 printf "%s.dest\0" | xargs -0 redo-ifchange  

  echo "$list" | while read f; do
    if [ -s "$f.dest" ]; then
      printf "%s\0" "$f.out"
    fi
  done | xargs -0 redo-ifchange

  echo "$list" | while read f; do
    fdir="${f%/*}"
    if [ -s "$f.dest" ]; then
      outfile="$OUTDIR/${fdir#$SRCDIR}/$(cat $f.dest)"
      mkdir -p "${outfile%/*}"
      cp --reflink -a "$f.out" "$outfile"
    fi
  done

}

dofile="$1"
shift
source "$dofile"

